### ISSUE TITLE
No "long_hint" in ContigFilter tutorial example

### ISSUE THREAD

**Issue by jungbluth** [kbase/kb_sdk_docs#40]
The "display.yaml" file auto-generated using ``kb-sdk init ...`` does not contain any long_hints. The tutorial page <https://kbase.github.io/kb_sdk_docs/tutorial/6_inputsoutputs.html> indicates that these should be present.

**Comment by jayrbolton** [comment]
I think it's optional. Are you suggesting we should leave it out of the docs on this page?

**Comment by jungbluth** [comment]
Seems like that would be the easiest way to go - right? If so, then I'll make the change with the other commits I've been working up. Will send a large pull request sometime soon.

**Comment by jayrbolton** [comment]
:+1: :zap:
